name: Conventional Commits

on:
    pull_request:
        branches: [main]

jobs:
    build:
        name: Conventional Commits
        runs-on: blacksmith
        steps:
            - uses: actions/checkout@v5

            - uses: gentleseal/action-conventional-commits@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
